# start f3 dev environment w/ docker-compose
services:

  app:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - LOCAL_DEVELOPMENT=true
      - DATABASE_HOST=db
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: ["nodemon", "--exec", "python main.py", "-e", "py"]


  db:
    image: postgres:16
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: f3
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
